export const products = [
  // Electronics
  {
    id: 1,
    slug: "amazon-echo-studio",
    name: "Amazon Echo Studio",
    category: "Electronics",
    price: 199.99,
    rating: 4.7,
    reviews: 28542,
    image: "https://m.media-amazon.com/images/I/71BRtVq+uWL._AC_SL1500_.jpg",
    link: "https://www.amazon.com/dp/B0FBHDQ94L?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4cd3efdb787ed10d584a3acabde6d449&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium smart speaker with immersive, room-filling sound, spatial audio processing, and Alexa voice control for the ultimate listening experience",
    longDescription:
      "Amazon Echo Studio delivers studio-quality sound with five strategically positioned speakers for powerful bass, dynamic midrange, and crisp highs. Featuring Dolby Atmos and spatial audio processing technology, it adapts to any room's acoustics for an immersive 3D audio experience. Control your music, smart home, and more with Alexa.",
    features: [
      "Dolby Atmos spatial audio",
      "5 directional speakers",
      "Automatic room adaptation",
      "Alexa built-in",
      "Smart home hub",
      "Hi-res lossless audio",
    ],
    specs: {
      Brand: "Amazon",
      Model: "Echo Studio",
      Connectivity: "Wi-Fi, Bluetooth, Zigbee",
      Color: "Charcoal",
      Weight: "7.7 lbs",
    },
  },
  {
    id: 2,
    slug: "amazon-fire-tv-stick-4k-select-newest-model",
    name: "Amazon Fire TV Stick 4K Select (newest model)",
    category: "Electronics",
    price: 54.99,
    rating: 4.6,
    reviews: 8912,
    image: "https://m.media-amazon.com/images/I/71B2hSrvyZL._AC_SY450_.jpg",
    link: "https://www.amazon.com/amazon-fire-tv-stick-4K-select/dp/B0C6W3D4RM?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description:
      "Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio",
    longDescription:
      "Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio. Access thousands of channels, apps, and Alexa skills with this powerful streaming device.",
    features: ["4K Ultra HD streaming", "Dolby Vision & HDR10+", "Dolby Atmos audio", "Alexa voice remote"],
    specs: { Resolution: "4K Ultra HD", Streaming: "Wi-Fi 6", Voice: "Alexa", Storage: "8GB" },
  },
  {
    id: 3,
    slug: "apple-airpods-pro-2-wireless-earbuds",
    name: "Apple AirPods Pro 2 Wireless Earbuds",
    category: "Electronics",
    price: 249.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 32456,
    image: "https://m.media-amazon.com/images/I/611pEx7220L._AC_SX522_.jpg",
    link: "https://www.amazon.com/Apple-Cancellation-Transparency-Personalized-High-Fidelity/dp/B0D1XD1ZV3?&linkCode=ll1&tag=marketplaza0b-20&linkId=04a9286d70d9246ac7e6693261e914f9&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium wireless earbuds with adaptive active noise cancellation, transparency mode, and personalized spatial audio",
    longDescription:
      "Premium wireless earbuds with up to 2x more active noise cancellation than the previous generation. Features Adaptive Audio that automatically adjusts noise control to your environment and personalized spatial audio for an immersive listening experience.",
    features: [
      "Active Noise Cancellation",
      "Adaptive Audio",
      "Transparency mode",
      "Personalized Spatial Audio",
      "Up to 6 hours listening time",
    ],
    specs: {
      Brand: "Apple",
      Model: "AirPods Pro 2",
      Battery: "Up to 30 hours with case",
      Connectivity: "Bluetooth 5.3",
    },
  },
  {
    id: 4,
    slug: "anker-power-bank-powercore-10k",
    name: "Anker Power Bank (PowerCore 10K)",
    category: "Electronics",
    price: 29.99,
    rating: 4.7,
    reviews: 18765,
    image: "https://m.media-amazon.com/images/I/71JJLJnwREL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Anker-Travel-Ready-Technology-High-Speed-Output%EF%BC%88Black%EF%BC%89%EF%BC%8C1pack/dp/B0D5CLSMFB?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Ultra-compact 10,000mAh portable charger with PowerIQ technology for fast charging on the go",
    longDescription:
      "Ultra-compact 10,000mAh portable charger with PowerIQ technology that intelligently identifies your device for the fastest possible charge. Slim design fits easily in pockets and bags while providing multiple full phone charges.",
    features: ["10,000mAh capacity", "PowerIQ fast charging", "Ultra-compact design", "Universal compatibility"],
    specs: { Capacity: "10,000mAh", Output: "12W", Weight: "6.56 oz", Ports: "USB-A" },
  },
  {
    id: 5,
    slug: "samsung-galaxy-s25-ultra",
    name: "SAMSUNG Galaxy S25 Ultra",
    category: "Electronics",
    price: 1299.99,
    rating: 4.9,
    reviews: 4567,
    image: "https://m.media-amazon.com/images/I/61n0lmxP5-L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Smartphone-Unlocked-Processor-Manufacturer-Warranty/dp/B0DP3G4GVQ?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description:
      "Flagship unlocked smartphone with advanced processor, stunning display, and professional-grade camera system",
    longDescription:
      "Flagship unlocked smartphone featuring the latest Snapdragon processor, stunning 6.8-inch Dynamic AMOLED display with 120Hz refresh rate, and a professional quad-camera system with advanced AI features for stunning photos and videos.",
    features: [
      '6.8" Dynamic AMOLED display',
      "Snapdragon processor",
      "Quad camera system",
      "5000mAh battery",
      "S Pen included",
    ],
    specs: { Display: '6.8" AMOLED', Storage: "256GB", RAM: "12GB", Camera: "200MP main" },
  },

  // Home & Kitchen
  {
    id: 6,
    slug: "instant-pot-duo-7-in-1-electric-pressure-cooker",
    name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    category: "Home & Kitchen",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviews: 142567,
    image: "https://m.media-amazon.com/images/I/71Z401LjFFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Instant-Pot-Multi-Use-Programmable-Pressure/dp/B00FLYWNYQ?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description:
      "Multi-functional programmable cooker combining pressure cooker, slow cooker, rice cooker, steamer, and more",
    longDescription:
      "7-in-1 programmable cooker that replaces multiple kitchen appliances. Functions as pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer. Makes cooking fast, easy, and convenient.",
    features: ["7-in-1 functionality", "14 smart programs", "6-quart capacity", "Stainless steel pot"],
    specs: { Capacity: "6 Quart", Functions: "7-in-1", Wattage: "1000W", Material: "Stainless Steel" },
  },
  {
    id: 7,
    slug: "ninja-air-fryer",
    name: "Ninja Air Fryer",
    category: "Home & Kitchen",
    price: 89.99,
    rating: 4.8,
    reviews: 67234,
    image: "https://m.media-amazon.com/images/I/71+8uTMDRFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Ninja-AF101-Fryer-Black-gray/dp/B07FDJMC9Q?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Compact air fryer with wide temperature range for guilt-free crispy favorites using little to no oil",
    longDescription:
      "Compact yet powerful air fryer that uses rapid air circulation technology to cook food with up to 75% less fat than traditional frying methods. Wide temperature range allows for versatile cooking from dehydrating to air frying.",
    features: ["4-quart capacity", "400°F max temperature", "Dishwasher safe basket", "Compact design"],
    specs: { Capacity: "4 Quart", Temperature: "105-400°F", Wattage: "1550W", Coating: "Nonstick" },
  },
  {
    id: 8,
    slug: "zinus-12-inch-king-green-tea-memory-foam-mattress",
    name: "ZINUS 12 Inch King Green Tea Memory Foam Mattress",
    category: "Home & Kitchen",
    price: 319.99,
    originalPrice: 449.99,
    rating: 4.6,
    reviews: 28945,
    image: "https://m.media-amazon.com/images/I/81XzXrlHljL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Zinus-Mattress-Fiberglass-Pressure-Certified/dp/B0CKZ1CK1H?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium memory foam mattress infused with green tea extract for natural odor control and pressure relief",
    longDescription:
      "Premium 12-inch memory foam mattress featuring green tea extract infusion for natural freshness and odor control. Multiple layers of foam provide superior pressure relief and support for a restful night's sleep.",
    features: ["Green tea infusion", "12-inch thickness", "Pressure relieving foam", "CertiPUR-US certified"],
    specs: { Size: "King", Thickness: "12 inches", Material: "Memory Foam", Certification: "CertiPUR-US" },
  },
  {
    id: 9,
    slug: "rubbermaid-brilliance-storage-container-set",
    name: "Rubbermaid Brilliance Storage Container Set",
    category: "Home & Kitchen",
    price: 39.99,
    rating: 4.8,
    reviews: 45123,
    image: "https://m.media-amazon.com/images/I/81Ap89R-ajL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Rubbermaid-Brilliance-Storage-Container-BPA-free/dp/B079M8FPTW?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "BPA-free leak-proof food storage containers with airtight seals and crystal-clear visibility",
    longDescription:
      "Premium food storage containers featuring crystal-clear Tritan material for easy visibility and 100% leak-proof seals. Microwave, dishwasher, and freezer safe for ultimate convenience in meal prep and storage.",
    features: ["100% leak-proof", "Crystal-clear Tritan", "Microwave & dishwasher safe", "Modular stacking"],
    specs: { Material: "BPA-free Tritan", Set: "14-piece", "Seal Type": "Leak-proof latch", Uses: "Multi-purpose" },
  },
  {
    id: 10,
    slug: "shark-navigator-lift-away-professional",
    name: "Shark Navigator Lift-Away Professional",
    category: "Home & Kitchen",
    price: 199.99,
    rating: 4.7,
    reviews: 78234,
    image: "https://m.media-amazon.com/images/I/71ybuaqVLwL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Shark-Navigator-Professional-Anti-Allergy-NV360/dp/B0D7QLQNS5?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Powerful upright vacuum with lift-away technology and anti-allergen complete seal",
    longDescription:
      "Professional upright vacuum with powerful suction and complete seal technology to trap dust and allergens. Features swivel steering for easy navigation around furniture and a lift-away canister for portable cleaning.",
    features: ["Anti-Allergy Complete Seal", "HEPA filter", "Swivel steering", "Lift-Away technology"],
    specs: { Type: "Upright", Filtration: "HEPA", Capacity: "2.2 Quarts", Cord: "25 ft" },
  },

  // Beauty & Personal Care
  {
    id: 11,
    slug: "cerave-skin-renewing-night-cream",
    name: "CeraVe Skin Renewing Night Cream",
    category: "Beauty & Personal Care",
    price: 18.99,
    rating: 4.6,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/71r7bLsvaVL._SX466_.jpg",
    link: "https://www.amazon.com/CeraVe-Skin-Renewing-Night-Cream/dp/B00SNPCSUY?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Peptide-rich night cream with hyaluronic acid for skin renewal and intense moisture",
    longDescription:
      "Nourishing night cream formulated with three essential ceramides, hyaluronic acid, and peptide complex to help restore and maintain the skin's natural protective barrier while you sleep. Non-comedogenic and fragrance-free.",
    features: ["3 essential ceramides", "Hyaluronic acid", "Peptide complex", "Fragrance-free"],
    specs: { Size: "1.7 oz", Type: "Night Cream", Skin: "All types", Formula: "Non-comedogenic" },
  },
  {
    id: 12,
    slug: "the-ordinary-hyaluronic-acid-2-b5",
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    category: "Beauty & Personal Care",
    price: 7.99,
    rating: 4.5,
    reviews: 89123,
    image: "https://m.media-amazon.com/images/I/61eH32lVpdL._SX522_.jpg",
    link: "https://www.amazon.com/Ordinary-Hyaluronic-Acid-2-30ml/dp/B01MYEZPC8?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Concentrated hydration serum with multi-weight hyaluronic acid molecules for plump skin",
    longDescription:
      "Lightweight water-based serum combining low, medium, and high molecular weight hyaluronic acid molecules along with a next-generation HA crosspolymer for multi-depth hydration. Enhanced with vitamin B5 for improved surface hydration.",
    features: ["Multi-weight hyaluronic acid", "Vitamin B5", "Lightweight texture", "Deep hydration"],
    specs: { Size: "30ml", Type: "Serum", Concentration: "2%", Vegan: "Yes" },
  },
  {
    id: 13,
    slug: "laneige-lip-sleeping-mask",
    name: "LANEIGE Lip Sleeping Mask",
    category: "Beauty & Personal Care",
    price: 24.0,
    rating: 4.7,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/51H5SkeGANL._SX522_.jpg",
    link: "https://www.amazon.com/Laneige-Sleeping-Berry/dp/B07XXPHQZK?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Overnight lip treatment with berry extract for soft, moisturized lips by morning",
    longDescription:
      "Overnight lip treatment featuring Berry Mix Complex™ rich in antioxidants and Vitamin C. The balmy texture forms a protective film that locks in moisture and active ingredients for visibly smoother, more supple lips by morning.",
    features: ["Berry Mix Complex", "Overnight moisture", "Antioxidant-rich", "Smooth texture"],
    specs: { Size: "20g", Type: "Lip Mask", Flavor: "Berry", Use: "Overnight" },
  },
  {
    id: 14,
    slug: "mielle-rosemary-mint-scalp-hair-oil",
    name: "Mielle Rosemary Mint Scalp & Hair Oil",
    category: "Beauty & Personal Care",
    price: 10.99,
    rating: 4.6,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/61n1krgI+tL._SX466_.jpg",
    link: "https://www.amazon.com/Mielle-Rosemary-Mint-Scalp-Strengthening/dp/B07N7PK9QK?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Biotin-enriched scalp treatment oil with rosemary and mint for healthy hair growth",
    longDescription:
      "Biotin-enriched scalp treatment oil with rosemary and mint for healthy hair growth. Helps nourish the scalp and strengthen hair while promoting growth.",
    features: ["Biotin enriched", "Rosemary & mint", "Promotes hair growth", "Nourishing formula"],
    specs: { Size: "2 oz", Type: "Scalp Oil", KeyIngredients: "Rosemary, Mint, Biotin" },
  },
//   {
//     id: 15,
//     slug: "elf-power-grip-primer",
//     name: "e.l.f. Power Grip Primer",
//     category: "Beauty & Personal Care",
//     price: 10.0,
//     rating: 4.6,
//     reviews: 123456,
//     image: "/elf-power-grip-primer-makeup-product.jpg",
//     link: "https://www.amazon.com/l-f-Power-Grip-Primer-Enhancing/dp/B084Q5CQS9?&linkCode=ll1&tag=marketplaza0b-20&linkId=e1406fa0fbd1f28cd4e4fb1dcf3d4868&language=en_US&ref_=as_li_ss_tl",
//     description: "Gel-based face primer with a tacky feel that grips makeup for long-lasting wear",
//     longDescription:
//       "Gel-based face primer with a tacky feel that grips makeup for long-lasting wear. Hydrates skin while creating the perfect base for foundation and other makeup.",
//     features: ["Tacky gel formula", "Long-lasting hold", "Hydrating", "Cruelty-free"],
//     specs: { Size: "0.74 oz", Type: "Primer", Finish: "Dewy", CrueltyFree: "Yes" },
//   },

  // Clothing, Shoes & Jewelry
  {
    id: 16,
    slug: "hanes-mens-ecosmart-fleece-sweatshirt",
    name: "Hanes Men's EcoSmart Fleece Sweatshirt",
    category: "Clothing, Shoes & Jewelry",
    price: 12.99,
    rating: 4.6,
    reviews: 56789,
    image: "https://m.media-amazon.com/images/I/81D+bCgn8hL._AC_SX569_.jpg",
    link: "https://www.amazon.com/Hanes-EcoSmart-Fleece-Sweatshirt-Stonewashed/dp/B0721C21RJ?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Comfortable crewneck sweatshirt made with recycled polyester for sustainable warmth",
    longDescription:
      "Classic crewneck sweatshirt made with EcoSmart fleece containing up to 5% recycled polyester from plastic bottles. Soft, medium-weight fabric provides warmth without bulk for comfortable everyday wear.",
    features: ["EcoSmart fleece", "Ribbed cuffs", "Pill-resistant", "Tag-free"],
    specs: { Material: "50/50 Cotton/Poly", Fit: "Regular", Weight: "Medium", Eco: "5% Recycled" },
  },
  {
    id: 17,
    slug: "hanes-full-zip-ecosmart-fleece-hoodie",
    name: "Hanes Full-Zip EcoSmart Fleece Hoodie",
    category: "Clothing, Shoes & Jewelry",
    price: 16.99,
    rating: 4.5,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/71QyRZzbaUL._AC_SX569_.jpg",
    link: "https://www.amazon.com/Hanes-Full-zip-Eco-smart-athletic-sweatshirts/dp/B00JUM4CT4?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Classic zip-up hoodie with eco-friendly fabric and comfortable athletic fit",
    longDescription:
      "Full-zip hoodie featuring EcoSmart fleece made with up to 5% recycled polyester. Full-length zipper allows for easy on/off and ventilation control. Kangaroo pocket provides convenient storage for essentials.",
    features: ["Full-zip design", "Kangaroo pocket", "EcoSmart fleece", "Adjustable hood"],
    specs: { Material: "50/50 blend", Closure: "Full-zip", Pockets: "Kangaroo", Fit: "Regular" },
  },
  {
    id: 18,
    slug: "adidas-mens-cloudfoam-pure-2-0-sneaker",
    name: "adidas Men's Cloudfoam Pure 2.0 Sneaker",
    category: "Clothing, Shoes & Jewelry",
    price: 65.0,
    rating: 4.7,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/71JsiyZWwyL._AC_SY575_.jpg",
    link: "https://www.amazon.com/adidas-Racer-Adapt-Sneaker-Black/dp/B0CKMC1BGB?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Lightweight running-inspired sneakers with cloudfoam cushioning for all-day comfort",
    longDescription:
      "Running-inspired sneakers featuring a breathable mesh upper and Cloudfoam midsole for step-in comfort and superior cushioning. Slip-on design with elastic laces makes them easy to wear while maintaining a secure fit.",
    features: ["Cloudfoam cushioning", "Mesh upper", "Slip-on design", "Flexible sole"],
    specs: { Brand: "adidas", Type: "Running shoe", Upper: "Mesh", Sole: "Rubber" },
  },
  {
    id: 19,
    slug: "levis-mens-511-slim-fit-jeans",
    name: "Levi's Men's 511 Slim Fit Jeans",
    category: "Clothing, Shoes & Jewelry",
    price: 59.99,
    rating: 4.6,
    reviews: 78901,
    image: "https://m.media-amazon.com/images/I/81HRsNLuziL._AC_SX466_.jpg",
    link: "https://www.amazon.com/Levis-Mens-Jeans-Stretch-Panda/dp/B072NGDWDY?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Classic slim-fit jeans with stretch denim for comfortable, modern style",
    longDescription:
      "Iconic 511 Slim Fit jeans featuring a slim fit through the hip and thigh with a slightly tapered leg. Made with premium stretch denim for comfortable movement while maintaining the classic Levi's quality and style.",
    features: ["Slim fit", "Stretch denim", "Five-pocket styling", "Zip fly"],
    specs: { Fit: "Slim", Rise: "Medium", Material: "Stretch Denim", Closure: "Zipper" },
  },
  {
    id: 20,
    slug: "casio-mens-duro-analog-watch",
    name: "Casio Men's Duro Analog Watch",
    category: "Clothing, Shoes & Jewelry",
    price: 54.95,
    rating: 4.7,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/61nHUVwR65L._AC_SY550_.jpg",
    link: "https://www.amazon.com/Casio-MDV106-1AV-Analog-Watch-Black/dp/B009KYJAJY?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Durable dive-style watch with 200M water resistance and reliable quartz movement",
    longDescription:
      "Professional dive-style analog watch featuring 200-meter water resistance, unidirectional rotating bezel, and luminous hands and markers for underwater visibility. Durable resin band and reliable Japanese quartz movement.",
    features: ["200m water resistant", "Rotating bezel", "Luminous markers", "Quartz movement"],
    specs: { Movement: "Quartz", "Water Resistance": "200m", Display: "Analog", Band: "Resin" },
  },

  // Toys & Games
  {
    id: 21,
    slug: "lego-classic-medium-creative-brick-box",
    name: "LEGO Classic Medium Creative Brick Box",
    category: "Toys & Games",
    price: 34.99,
    rating: 4.8,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/8160QjpuoOL._AC_SX679_.jpg",
    link: "https://www.amazon.com/LEGO-Classic-Medium-Creative-Brick/dp/B00NHQFA1I?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "484-piece creative building set with vibrant colors for endless imaginative possibilities",
    longDescription:
      "Creative building set featuring 484 pieces in 35 different colors for endless building possibilities. Includes windows, eyes, and wheels plus a building ideas booklet to inspire creativity and imagination.",
    features: ["484 pieces", "35 colors", "Building ideas included", "Classic LEGO bricks"],
    specs: { Pieces: 484, Ages: "4+", Theme: "Classic", Type: "Building Set" },
  },
  {
    id: 22,
    slug: "uno-card-game",
    name: "UNO Card Game",
    category: "Toys & Games",
    price: 5.99,
    rating: 4.9,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/91zZyNjPcLL._AC_SY879_.jpg",
    link: "https://www.amazon.com/Mattel-Games-Adults-Parties-Special/dp/B0D6X9T62X?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Classic family card game for 2-10 players with simple rules and fast-paced fun",
    longDescription:
      "Classic UNO game with a team play twist that adds a new level of strategy and excitement. Players work together with their teammate to be the first team to get rid of all their cards. Perfect for 4+ players.",
    features: ["Team gameplay", "4+ players", "Quick setup", "Travel-friendly"],
    specs: { Players: "4+", Ages: "7+", "Play Time": "30 min", Cards: "112" },
  },
  {
    id: 23,
    slug: "barbie-dreamhouse",
    name: "Barbie Dreamhouse",
    category: "Toys & Games",
    price: 199.99,
    rating: 4.7,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/71PFKADv6CL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Barbie-Dreamhouse-3-Story-Playset-Elevator/dp/B0BLJTJ38M?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "3-story dollhouse playset with working elevator and pool slide for imaginative play",
    longDescription:
      "Iconic 3-story Dreamhouse featuring 8 rooms, a working elevator, pool with slide, and 75+ accessories. Interactive features include lights, sounds, and transformation play pieces for endless storytelling possibilities.",
    features: ["3 stories, 8 rooms", "Working elevator", "Pool with slide", "75+ accessories"],
    specs: { Height: "3.75 feet", Rooms: "8", Features: "Lights & sounds", Ages: "3+" },
  },
  {
    id: 24,
    slug: "nintendo-switch-super-mario-bros-wonder-bundle",
    name: "Nintendo Switch with Super Mario Bros. Wonder Bundle",
    category: "Toys & Games",
    price: 349.99,
    rating: 4.9,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/715AHrLja3L._SX522_.jpg",
    link: "https://www.amazon.com/Nintendo-Switch-Mario-World-Bundle-2/dp/B0FC5FJZ9Z?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Hybrid gaming console bundle with the latest Mario adventure game included",
    longDescription:
      "Next-generation Switch console with enhanced graphics and performance. Bundle includes Super Mario Bros. Wonder game. Play on TV at home or take it on the go for portable gaming experiences.",
    features: ["Portable & TV mode", "Enhanced graphics", "Super Mario Bros. Wonder included", "Multiplayer ready"],
    specs: { Screen: '7" OLED', Storage: "64GB", Battery: "9 hours", Controllers: "2 Joy-Cons" },
  },
  {
    id: 25,
    slug: "play-doh-modeling-compound-36-pack",
    name: "Play-Doh Modeling Compound 36-Pack",
    category: "Toys & Games",
    price: 19.99,
    rating: 4.8,
    reviews: 56789,
    image: "https://m.media-amazon.com/images/I/71LqxbA1WCL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Play-Doh-Modeling-Compound-Non-Toxic-Exclusive/dp/B00JM5GW10?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Non-toxic modeling compound in rainbow colors for creative sculpting and play",
    longDescription:
      "Classic modeling compound in 36 different vibrant colors. Non-toxic formula is safe for creative play. Each can contains 2 ounces of soft, pliable compound perfect for molding, sculpting, and imaginative creations.",
    features: ["36 vibrant colors", "Non-toxic formula", "2 oz per can", "Soft & pliable"],
    specs: { Colors: "36", Amount: "72 oz total", Ages: "2+", Safe: "Non-toxic" },
  },

  // Health & Household / Baby
  {
    id: 26,
    slug: "pampers-sensitive-baby-wipes",
    name: "Pampers Sensitive Baby Wipes",
    category: "Health & Household / Baby",
    price: 19.99,
    rating: 4.8,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/71NqHkGRN1L._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg",
    link: "https://www.amazon.com/Pampers-Wipes-Sensitive-Perfume-Multi/dp/B0BJ13K7FR?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Hypoallergenic baby wipes with gentle cleansing lotion for sensitive skin",
    longDescription:
      "Hypoallergenic and perfume-free baby wipes with a clinically proven mild formula. Thick and gentle, these wipes are perfect for sensitive skin and provide a thorough clean with every wipe.",
    features: ["Hypoallergenic", "Perfume-free", "Clinically proven mild", "Thick & gentle"],
    specs: { Count: "12 packs", "Per Pack": "56 wipes", Total: "672 wipes", pH: "Balanced" },
  },
  {
    id: 27,
    slug: "charmin-ultra-strong-toilet-paper",
    name: "Charmin Ultra Strong Toilet Paper",
    category: "Health & Household / Baby",
    price: 29.99,
    rating: 4.7,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/81Xyre0z0VL._AC_SX679_PIbundle-24,TopRight,0,0_SH20_.jpg",
    link: "https://www.amazon.com/Charmin-Toilet-Family-Cushiony-Sheets/dp/B0798DVT68?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "4X stronger bath tissue with cushiony comfort in family mega rolls",
    longDescription:
      "Luxuriously soft and absorbent 2-ply toilet paper with Charmin's signature cushiony texture. Septic-safe and clog-safe when used as directed. Each Family Mega Roll has 264 sheets.",
    features: ["2-ply softness", "Cushiony texture", "Septic-safe", "Clog-safe"],
    specs: { Rolls: "24 Family Mega", "Sheets per Roll": 264, Ply: "2-ply", Safe: "Septic-safe" },
  },
  {
    id: 28,
    slug: "natures-way-sambucus-elderberry-gummies",
    name: "Nature's Way Sambucus Elderberry Gummies",
    category: "Health & Household / Baby",
    price: 14.99,
    rating: 4.6,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/7134HKzZjdL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Natures-Way-Elderberry-Vegetarian-Packaging/dp/B00MJ7VL1O?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Immune support gummies with black elderberry extract and vitamin C",
    longDescription:
      "Delicious vegetarian gummies made with premium black elderberry extract plus vitamin C and zinc for immune support. Great tasting and pectin-based formula suitable for the whole family.",
    features: ["Black elderberry", "Vitamin C & Zinc", "Vegetarian", "Great taste"],
    specs: { Count: "60 gummies", Servings: "30", Type: "Gummy", Vegetarian: "Yes" },
  },
  {
    id: 29,
    slug: "huggies-natural-care-sensitive-baby-wipes",
    name: "Huggies Natural Care Sensitive Baby Wipes",
    category: "Health & Household / Baby",
    price: 21.99,
    rating: 4.8,
    reviews: 56789,
    image: "https://m.media-amazon.com/images/I/81FlNgJOeqL._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg",
    link: "https://www.amazon.com/HUGGIES-Natural-Unscented-Sensitive-Water-Based/dp/B07SCL613T?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Unscented plant-based wipes with 99% water for gentle baby care",
    longDescription:
      "Water-based baby wipes made with 99% purified water and gentle plant-derived ingredients. Unscented and hypoallergenic formula is clinically proven gentle for sensitive skin. Thick and absorbent.",
    features: ["99% water", "Plant-derived", "Unscented", "Hypoallergenic"],
    specs: { Packs: "12", "Per Pack": "56 wipes", Total: "672 wipes", Base: "Water" },
  },
  {
    id: 30,
    slug: "philips-avent-natural-baby-bottle",
    name: "Philips Avent Natural Baby Bottle",
    category: "Health & Household / Baby",
    price: 29.99,
    rating: 4.7,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/71IsWBuTvfL._SX466_.jpg",
    link: "https://www.amazon.com/Philips-Natural-Response-SCY910-04/dp/B098YHHV3Q?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Anti-colic baby bottles with natural response nipple for comfortable feeding",
    longDescription:
      "Premium glass baby bottles featuring Natural Response nipples with an innovative opening that releases milk only when baby actively drinks. Glass material is easy to clean and naturally BPA-free.",
    features: ["Natural Response nipple", "Glass material", "Anti-colic", "BPA-free"],
    specs: { Material: "Glass", Size: "8 oz", Count: "4 bottles", Nipple: "Natural Response" },
  },

  // Sports & Outdoors
  {
    id: 31,
    slug: "fitbit-charge-6-fitness-tracker",
    name: "Fitbit Charge 6 Fitness Tracker",
    category: "Sports & Outdoors",
    price: 159.95,
    rating: 4.5,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/61ZtqtvoD2L._AC_SX466_.jpg",
    link: "https://www.amazon.com/Fitbit-Exercise-Equipment-6-Months-Membership/dp/B0CC62ZG1M?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Advanced fitness tracker with heart rate monitoring, GPS, and sleep tracking",
    longDescription:
      "Advanced fitness tracker with built-in GPS, 24/7 heart rate monitoring, and Google apps integration. Track workouts, sleep, stress, and more. Includes 6-month Fitbit Premium membership.",
    features: ["Built-in GPS", "Heart rate monitoring", "Google apps", "40+ exercise modes"],
    specs: { Display: "AMOLED", Battery: "7 days", "Water Resistance": "50m", Connectivity: "Bluetooth" },
  },
  {
    id: 32,
    slug: "coleman-sleeping-bag",
    name: "Coleman Sleeping Bag",
    category: "Sports & Outdoors",
    price: 29.99,
    rating: 4.6,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/61aUr3tBexL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Coleman-Weatherproof-Festivals-Backyard-Sleepovers/dp/B0D7QLQNS5?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "All-season rectangular sleeping bag with weather-resistant design for camping",
    longDescription:
      "Weatherproof dome tent featuring WeatherTec system with patented welded floors and inverted seams to keep water out. Easy setup with snag-free Insta-Clip pole attachments. Fits 2-4 people.",
    features: ["WeatherTec system", "Easy setup", "Vented windows", "E-port for power"],
    specs: { Capacity: "4 person", Size: "8x7 ft", Height: "4.5 ft", Setup: "Quick" },
  },
  {
    id: 33,
    slug: "under-armour-mens-charged-assert-10",
    name: "Under Armour Men's Charged Assert 10",
    category: "Sports & Outdoors",
    price: 70.0,
    rating: 4.6,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/61O30g0cZmL._AC_SY575_.jpg",
    link: "https://www.amazon.com/Under-Armour-Charged-Assert-Running/dp/B09XBWQ9Y9?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Performance running shoes with charged cushioning for responsive comfort",
    longDescription:
      "Versatile running shoes featuring Charged Cushioning midsole for responsive comfort and support. Lightweight mesh upper provides breathability, while durable leather overlays add stability and structure.",
    features: ["Charged Cushioning", "Mesh upper", "Durable overlays", "Flexible sole"],
    specs: { Type: "Running", Cushioning: "Charged", Upper: "Mesh & Leather", Sole: "Rubber" },
  },
  {
    id: 34,
    slug: "garmin-forerunner-255-gps-running-watch",
    name: "Garmin Forerunner 255 GPS Running Watch",
    category: "Sports & Outdoors",
    price: 349.99,
    rating: 4.7,
    reviews: 8901,
    image: "https://m.media-amazon.com/images/I/518z0My1ZlS._AC_SX679_.jpg",
    link: "https://www.amazon.com/Garmin-Forerunner-Running-Suggested-Workouts/dp/B092RCLKHN?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Advanced GPS smartwatch with race widget, training status, and performance metrics",
    longDescription:
      "Easy-to-use GPS running watch with suggested workouts based on your training history and fitness level. Features PacePro pacing guidance, running dynamics, and all-day health monitoring including heart rate and stress.",
    features: ["Built-in GPS", "Suggested workouts", "PacePro guidance", "Health monitoring"],
    specs: { Display: "Sunlight-readable", Battery: "2 weeks", GPS: "Built-in", "Water Rating": "5 ATM" },
  },
  {
    id: 35,
    slug: "yeti-rambler-20-oz-tumbler",
    name: "YETI Rambler 20 oz Tumbler",
    category: "Sports & Outdoors",
    price: 35.0,
    rating: 4.9,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/51kXewLNVGL._AC_SX679_.jpg",
    link: "https://www.amazon.com/YETI-Rambler-Stainless-Insulated-MagSlider/dp/B08D3VPRQ1?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Stainless steel insulated tumbler with MagSlider lid for hot or cold beverages",
    longDescription:
      "Durable travel mug with double-wall vacuum insulation to keep drinks hot or cold for hours. Features MagSlider lid for easy opening and closing, plus a durable handle for convenient carrying. Dishwasher safe.",
    features: ["Double-wall insulated", "MagSlider lid", "Durable handle", "Dishwasher safe"],
    specs: { Capacity: "20 oz", Material: "Stainless Steel", Insulation: "Vacuum", Handle: "Yes" },
  },

  // Books
  {
    id: 36,
    slug: "atomic-habits-by-james-clear",
    name: "Atomic Habits by James Clear",
    category: "Books",
    price: 16.99,
    rating: 4.8,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/71F4+7rk2eL._SX342_.jpg",
    link: "https://www.amazon.com/Atomic-Habits-James-Clear-audiobook/dp/B07RFSSYBH?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Proven strategies for building good habits and breaking bad ones with tiny changes",
    longDescription:
      "Practical guide revealing how tiny changes can lead to remarkable results. Learn proven strategies to build good habits, break bad ones, and master the tiny behaviors that lead to remarkable outcomes.",
    features: ["Habit formation", "Behavior change", "Practical strategies", "Real examples"],
    specs: { Author: "James Clear", Pages: "320", Format: "Hardcover", Publisher: "Avery" },
  },
  {
    id: 37,
    slug: "the-subtle-art-of-not-giving-a-fck",
    name: "The Subtle Art of Not Giving a F*ck",
    category: "Books",
    price: 15.99,
    rating: 4.6,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/81A5jQHA+lL._SX342_.jpg",
    link: "https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/B01I29Y344?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Counterintuitive approach to living a good life through accepting limitations",
    longDescription:
      "Counterintuitive approach to living a good life that challenges the conventional wisdom of positive thinking. Learn to embrace life's limitations and focus your energy on what truly matters.",
    features: ["Counterintuitive wisdom", "Life philosophy", "Real talk", "Practical advice"],
    specs: { Author: "Mark Manson", Pages: "224", Format: "Paperback", Language: "English" },
  },
  {
    id: 38,
    slug: "harry-potter-and-the-sorcerers-stone",
    name: "Harry Potter and the Sorcerer's Stone",
    category: "Books",
    price: 8.99,
    rating: 4.9,
    reviews: 234567,
    image: "https://m.media-amazon.com/images/I/91eopoUCjLL._SX342_.jpg",
    link: "https://www.amazon.com/Harry-Potter-Sorcerers-Stone-Book/dp/B017V4IMVQ?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "First book in the magical Harry Potter series following the young wizard's adventures",
    longDescription:
      "Magical beginning of the beloved series following orphan Harry Potter who discovers he's a wizard on his 11th birthday. Join Harry as he attends Hogwarts School of Witchcraft and Wizardry and uncovers his extraordinary destiny.",
    features: ["Fantasy adventure", "Coming of age", "Magic & friendship", "Series starter"],
    specs: { Author: "J.K. Rowling", Pages: "309", Series: "Book 1 of 7", Format: "Hardcover" },
  },
  {
    id: 39,
    slug: "the-48-laws-of-power",
    name: "The 48 Laws of Power",
    category: "Books",
    price: 21.99,
    rating: 4.7,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/71s-d6iLlaL._SX342_.jpg",
    link: "https://www.amazon.com/48-Laws-of-Power-Robert-Greene-audiobook/dp/B00X0TKUS0?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Distilled wisdom of masters who wielded power throughout history",
    longDescription:
      "Timeless guide distilling 3,000 years of power dynamics into 48 laws. Learn to navigate complex social situations, understand manipulation tactics, and master the subtle art of power in all aspects of life.",
    features: ["Power dynamics", "Strategic thinking", "Historical examples", "Practical laws"],
    specs: { Author: "Robert Greene", Pages: "452", Format: "Paperback", Genre: "Self-help" },
  },

  // Pet Supplies
  {
    id: 40,
    slug: "furbo-dog-camera-with-360-view",
    name: "Furbo Dog Camera with 360° View",
    category: "Pet Supplies",
    price: 209.99,
    rating: 4.3,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/616wRFOTA5L._AC_SX466_.jpg",
    link: "https://www.amazon.com/Furbo-Camera-with-360%C2%B0-View/dp/B09GDQZLD1?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Smart pet camera with treat tossing, barking alerts, and full-room tracking",
    longDescription:
      "360-degree rotating pet camera with treat tossing capability, barking alerts, and two-way audio. Features Full HD video, night vision, and smart dog alerts to keep you connected with your furry friend from anywhere.",
    features: ["360° rotation", "Treat tossing", "Two-way audio", "Barking alerts", "Night vision"],
    specs: { Resolution: "1080p", Rotation: "360 degrees", Audio: "2-way", Connectivity: "Wi-Fi" },
  },
  {
    id: 51,
    slug: "amazon-basics-heavy-duty-pet-training-pads",
    name: "Amazon Basics Heavy-Duty Pet Training and Puppy Pads",
    category: "Pet Supplies",
    price: 19.99,
    rating: 4.6,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/71LHksRF15L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Amazon-Basics-Heavy-Duty-Absorbency-Regular/dp/B00MW8G62E?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Super-absorbent training pads with 5-layer protection for puppies and senior dogs",
    longDescription:
      "Heavy-duty absorbent training pads with 5-layer leak-proof design including quick-dry surface and built-in attractant. Perfect for puppy training, senior dogs, or pets with special needs.",
    features: ["5-layer protection", "Leak-proof backing", "Quick-dry surface", "Built-in attractant"],
    specs: { Size: "22 x 22 inches", Quantity: "100 count", Absorbency: "Heavy-duty", Type: "Disposable" },
  },
  {
    id: 52,
    slug: "furbo-dog-camera",
    name: "Furbo Dog Camera",
    category: "Pet Supplies",
    price: 169.99,
    rating: 4.3,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/616wRFOTA5L._AC_SX466_.jpg",
    link: "https://www.amazon.com/Furbo-Camera-with-360%C2%B0-View/dp/B09GDQZLD1?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Interactive pet camera with treat tossing, two-way audio, and barking alerts",
    longDescription:
      "Interactive pet camera with treat tossing, two-way audio, and barking alerts. Features Full HD video, night vision, and smart dog alerts to keep you connected with your furry friend.",
    features: ["Treat tossing", "Two-way audio", "Barking alerts", "Night vision", "Full HD"],
    specs: { Resolution: "1080p", Audio: "2-way", Connectivity: "Wi-Fi", NightVision: "Yes" },
  },
  {
    id: 53,
    slug: "kong-classic-dog-toy",
    name: "KONG Classic Dog Toy",
    category: "Pet Supplies",
    price: 12.99,
    rating: 4.8,
    reviews: 89012,
    image: "/kong-classic-red-rubber-dog-toy.jpg",
    link: "https://www.amazon.com/KONG-Classic-Durable-Natural-Rubber/dp/B0002AR0II?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Durable rubber toy for stuffing treats, promoting healthy play and mental stimulation",
    longDescription:
      "Durable rubber chew toy that can be stuffed with treats for mental stimulation and play. Its unpredictable bounce keeps dogs engaged, promoting healthy chewing habits.",
    features: ["Durable rubber", "Stuffable for treats", "Unpredictable bounce", "Promotes chewing"],
    specs: { Material: "Natural Rubber", Size: "Large", Color: "Red", Use: "Chew toy" },
  },
//   {
//     id: 54,
//     slug: "petsafe-automatic-ball-launcher",
//     name: "PetSafe Automatic Ball Launcher",
//     category: "Pet Supplies",
//     price: 139.99,
//     rating: 4.2,
//     reviews: 5678,
//     image: "/petsafe-automatic-ball-launcher-for-dogs.jpg",
//     link: "https://www.amazon.com/PetSafe-Automatic-Ball-Launcher-Dog/dp/B0721735K9?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
//     description: "Interactive automatic ball thrower for dogs with adjustable launch distances",
//     longDescription:
//       "Interactive ball thrower keeping dogs entertained with automatic fetching fun. Features adjustable range settings and multiple balls for extended play sessions.",
//     features: ["Automatic fetching", "Adjustable range", "Multiple balls", "Keeps dogs active"],
//     specs: { Type: "Ball Launcher", Power: "AC adapter", Range: "Adjustable", Balls: "Included" },
//   },
//   {
//     id: 55,
//     slug: "catit-flower-fountain",
//     name: "Catit Flower Fountain",
//     category: "Pet Supplies",
//     price: 29.99,
//     rating: 4.5,
//     reviews: 45678,
//     image: "/catit-flower-fountain-water-dispenser.jpg",
//     link: "https://www.amazon.com/Catit-Flower-Fountain-3-Liters/dp/B0146QXOB0?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
//     description: "3-liter pet water fountain with flower design encouraging cats to drink more water",
//     longDescription:
//       "Fresh flowing water fountain encouraging cats to drink more with flower design and triple action filter. Provides filtered water at multiple flow options for picky drinkers.",
//     features: ["Encourages hydration", "Flower design", "Triple action filter", "Multiple flow options"],
//     specs: { Capacity: "3 Liters", Filter: "Triple Action", Material: "BPA-free", Design: "Flower" },
//   },
  {
    id: 57,
    slug: "furminator-deshedding-tool",
    name: "FURminator Deshedding Tool",
    category: "Pet Supplies",
    price: 39.99,
    rating: 4.6,
    reviews: 67890,
    image: "/furminator-deshedding-grooming-tool.jpg",
    link: "https://www.amazon.com/FURminator-deShedding-Tool-Large-Dogs/dp/B0040QQ07C?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Professional grooming tool reducing shedding up to 90% for large dogs",
    longDescription:
      "Professional grooming tool reducing shedding up to 90% with stainless steel edge. Designed for long-haired dogs to effectively remove undercoat and loose hair.",
    features: ["Reduces shedding 90%", "Stainless steel edge", "For long hair", "Professional quality"],
    specs: { For: "Long Hair Dogs", Size: "Large", Type: "deShedding Tool", Material: "Stainless Steel" },
  },
//   {
//     id: 58,
//     slug: "smartykat-hot-pursuit-cat-toy",
//     name: "SmartyKat Hot Pursuit Cat Toy",
//     category: "Pet Supplies",
//     price: 14.99,
//     rating: 4.5,
//     reviews: 23456,
//     image: "/smartykat-hot-pursuit-electronic-cat-toy.jpg",
//     link: "https://www.amazon.com/SmartyKat-Hot-Pursuit-Electronic-Concealed/dp/B06WP7F8YC?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
//     description: "Electronic concealed motion cat toy with feather and random speed for active play",
//     longDescription:
//       "Electronic cat toy with concealed feather stimulating natural hunting instincts. Moves erratically to keep cats engaged and entertained.",
//     features: ["Concealed feather", "Stimulates hunting instinct", "Erratic movement", "Entertains cats"],
//     specs: { Type: "Electronic", Motion: "Concealed", Batteries: "Included", Material: "Plastic" },
//   },
//   {
//     id: 59,
//     slug: "petmate-two-door-top-load-kennel",
//     name: "Petmate Two Door Top Load Kennel",
//     category: "Pet Supplies",
//     price: 49.99,
//     rating: 4.6,
//     reviews: 34567,
//     image: "/petmate-two-door-pet-carrier-kennel.jpg",
//     link: "https://www.amazon.com/Petmate-Two-Door-Top-Load/dp/B00063KCS8?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
//     description: "Durable pet carrier with top and side entry for easy loading and secure travel",
//     longDescription:
//       "Durable pet carrier with top and side entry for safe comfortable travel. Features secure locking mechanism and ventilation for pet comfort.",
//     features: ["Top & side entry", "Secure locking", "Ventilated", "Durable construction"],
//     specs: { Size: "24 inch", Doors: "2", Material: "Plastic", Use: "Travel" },
//   },
  {
    id: 60,
    slug: "tetra-aquarium-cleaner-gravel-vacuum",
    name: "Tetra Aquarium Cleaner Gravel Vacuum",
    category: "Pet Supplies",
    price: 14.99,
    rating: 4.4,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/71POJ-eqDWL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Tetra-Cleaner-Gravel-Aquariums-Freshwater/dp/B091D3DTWS?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Easy-to-use aquarium vacuum for cleaning gravel and water changes",
    longDescription:
      "Easy-to-use aquarium vacuum and gravel cleaner that removes debris from gravel beds while performing water changes. Self-starting siphon design makes water changes simple and mess-free.",
    features: ["Gravel cleaning", "Water changing", "Self-starting siphon", "Easy to use"],
    specs: { Type: "Gravel Vacuum", Size: "16 inch", Use: "Freshwater tanks", Design: "Self-start" },
  },

  // Garden & Tools
  {
    id: 41,
    slug: "weber-spirit-e-310-gas-grill",
    name: "Weber Spirit E-310 Gas Grill",
    category: "Garden & Tools",
    price: 549.0,
    originalPrice: 599.0,
    rating: 4.7,
    reviews: 8901,
    image: "https://m.media-amazon.com/images/I/71vd9uEPNFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Weber-SPIRIT-3-Burner-Liquid-Propane/dp/B0DPH6NNTB?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "3-burner liquid propane grill with porcelain-enameled cooking grates and built-in thermometer",
    longDescription:
      "3-burner liquid propane gas grill with porcelain-enameled lid and cooking grates for perfect outdoor BBQ. Features 529 square inches of cooking space, powerful GS4 grilling system, and durable construction.",
    features: [
      "3 stainless steel burners",
      "Porcelain-enameled cast iron grates",
      "Built-in thermometer",
      "Side tables for prep",
    ],
    specs: { Fuel: "Liquid Propane", Burners: "3", "Cooking Area": "529 sq in", Material: "Stainless Steel" },
  },
  {
    id: 42,
    slug: "greenworks-40v-cordless-lawn-mower",
    name: "Greenworks 40V Cordless Lawn Mower",
    category: "Garden & Tools",
    price: 349.99,
    rating: 4.5,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/81hk0PGpklL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B09F9C3KFS?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Battery-powered push mower with 20-inch cutting deck and 2-in-1 mulching capability",
    longDescription:
      "Powerful 20-inch cordless mower with brushless motor and durable steel deck for efficient lawn care.",
    features: ["Brushless motor", "20-inch cutting deck", "Mulching capability", "Cordless"],
    specs: { Voltage: "40V", CuttingWidth: "20 inches", Battery: "Included", Deck: "Steel" },
  },
  {
    id: 43,
    slug: "best-choice-products-4-piece-patio-furniture-set",
    name: "Best Choice Products 4-Piece Patio Furniture Set",
    category: "Garden & Tools",
    price: 399.99,
    rating: 4.4,
    reviews: 3456,
    image: "https://m.media-amazon.com/images/I/71UDfsaOKvL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B09F3CWRRC?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Rattan wicker conversation set with cushions for outdoor comfort and style",
    longDescription:
      "Premium 4-piece outdoor conversation set featuring weather-resistant wicker and thick cushions. Includes two chairs, loveseat, and coffee table for comfortable outdoor lounging.",
    features: ["Weather-resistant wicker", "Thick cushions", "4-piece set", "Sturdy frame"],
    specs: { Pieces: "4", Material: "PE Wicker", Frame: "Steel", Cushions: "Included" },
  },
  {
    id: 44,
    slug: "blackdecker-20v-max-drill-home-tool-kit",
    name: "BLACK+DECKER 20V MAX Drill & Home Tool Kit",
    category: "Garden & Tools",
    price: 89.99,
    rating: 4.6,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/71CZ9FyVBhL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B07J66MY3Y?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "68-piece cordless drill kit with battery, charger, and essential hand tools",
    longDescription:
      "Complete 68-piece cordless drill kit with 20V MAX battery, charger, and essential hand tools for home projects. Ideal for DIY repairs, assembly, and general home improvement.",
    features: ["20V MAX battery", "68 pieces", "Includes drill & tools", "Compact storage case"],
    specs: { Voltage: "20V", Pieces: "68", Battery: "Included", Charger: "Included" },
  },
  {
    id: 45,
    slug: "sun-joe-electric-pressure-washer",
    name: "Sun Joe Electric Pressure Washer",
    category: "Garden & Tools",
    price: 149.99,
    rating: 4.5,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/81IY7R7mHfL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B0DBZM45GP?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "2030 PSI electric power washer for cleaning decks, driveways, and siding",
    longDescription:
      "Powerful 2030 PSI electric pressure washer with dual soap tanks and 5 quick-connect nozzles. Perfect for cleaning cars, decks, siding, driveways, and more.",
    features: ["2030 PSI", "Dual soap tanks", "5 quick-connect nozzles", "Compact design"],
    specs: { PSI: "2030", Power: "Electric", Nozzles: "5", SoapTanks: "Dual" },
  },
  {
    id: 46,
    slug: "kurapika-3-piece-outdoor-patio-bistro-set",
    name: "Kurapika 3-Piece Outdoor Patio Bistro Set",
    category: "Garden & Tools",
    price: 159.99,
    rating: 4.3,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71ZBHo8TceL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Kurapika-Furniture-Outdoor-Conversation-Backyard/dp/B0DP43X8ZJ?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Compact rattan bistro set perfect for balconies and small outdoor spaces",
    longDescription:
      "Compact 3-piece bistro set perfect for small spaces including balconies, patios, and poolside areas. Features 2 comfortable chairs and 1 side table. Weather-resistant construction for year-round use.",
    features: ["Compact design", "2 chairs + table", "Weather-resistant", "Small space friendly"],
    specs: { Pieces: "3", Style: "Bistro", "Space Type": "Small", Weather: "Resistant" },
  },
  {
    id: 47,
    slug: "devoko-5-pieces-patio-furniture-sets",
    name: "Devoko 5 Pieces Patio Furniture Sets",
    category: "Garden & Tools",
    price: 299.99,
    rating: 4.4,
    reviews: 5678,
    image: "https://m.media-amazon.com/images/I/81VhMt7V08L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Devoko-Furniture-Rattan-Cushion-Outdoor/dp/B0765VTBLV?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Manual wicker outdoor sectional with glass table and comfortable cushions",
    longDescription:
      "Comfortable 5-piece outdoor sectional with premium cushions. Durable hand-woven PE rattan over sturdy steel frame. Water-resistant cushion covers.",
    features: ["Hand-woven rattan", "Premium cushions", "5-piece set", "Water-resistant covers"],
    specs: { Pieces: "5", Weave: "Hand-woven PE", Frame: "Steel", Covers: "Water-resistant" },
  },
  {
    id: 48,
    slug: "qsun-4-piece-outdoor-patio-furniture",
    name: "Qsun 4-Piece Outdoor Patio Furniture",
    category: "Garden & Tools",
    price: 349.99,
    rating: 4.3,
    reviews: 2345,
    image: "https://m.media-amazon.com/images/I/71tXTDVLrFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Qsun-Furniture-Conversation-Backyard-Poolside/dp/B09CDNXK56?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Rattan conversation set ideal for backyard, poolside, or garden relaxation",
    longDescription:
      "Stylish 4-piece outdoor furniture set including 2 single chairs, 1 loveseat, and coffee table. Weather-resistant PE rattan and powder-coated steel frame with thick cushions for comfort.",
    features: ["4-piece set", "Weather-resistant", "Thick cushions", "Steel frame"],
    specs: { Pieces: "4", Material: "PE Rattan", Frame: "Steel", Cushions: "Included" },
  },
  {
    id: 49,
    slug: "mouse-station-bait-station",
    name: "Mouse Station Bait Station",
    category: "Garden & Tools",
    price: 24.99,
    rating: 4.5,
    reviews: 8901,
    image: "https://m.media-amazon.com/images/I/61Xjhe-7-1L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Mouse-Station-Keys-Required-Stations/dp/B0FDFHPVQ7?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Reusable rodent control station with key lock for safe pest management",
    longDescription:
      "Professional tamper-resistant mouse bait station with secure key-access system for safe pest control around homes, gardens, and outbuildings. Protects children and pets while effectively managing rodent problems.",
    features: ["Key-access security", "Tamper-resistant", "Weather-proof", "Refillable"],
    specs: { Type: "Bait Station", Access: "Key-locked", Use: "Indoor/Outdoor", Material: "Durable plastic" },
  },
  {
    id: 50,
    slug: "jamfly-outdoor-wicker-egg-chair",
    name: "JAMFLY Outdoor Wicker Egg Chair",
    category: "Garden & Tools",
    price: 279.99,
    rating: 4.6,
    reviews: 1234,
    image: "https://m.media-amazon.com/images/I/71ekHPtCxdL._AC_SX679_.jpg",
    link: "https://www.amazon.com/JAMFLY-Outdoor-Oversized-Lounger-Backyard/dp/B0D11DZZ5J?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Oversized wicker egg chair lounger perfect for backyard relaxation and outdoor comfort",
    longDescription:
      "Oversized wicker egg chair with sturdy steel stand and thick cushions creates a luxurious outdoor relaxation spot. Weather-resistant PE wicker construction perfect for patios, decks, and gardens.",
    features: ["Oversized design", "Steel stand included", "Thick cushions", "Weather-resistant wicker"],
    specs: { Weight: "Capacity 300 lbs", Material: "PE Wicker", Stand: "Steel", Cushion: "Removable" },
  },
];